### ISSUE TITLE
When accessing the Authn MFE first time, It shows "Authn | null" in the header

### ISSUE THREAD

**Issue by hinakhadim** [openedx/frontend-app-authn#1158]
Whenever I clicked on 'Sign In' button, it takes me to the Authn MFE. The issue is that it shows 'Authn | null' in the header. The reason is that in `public/index.html`, the header is `<title>Authn | <%= process.env.SITE_NAME %></title>`. For first time, the `process.env.SITE_NAME` is null and after that `mergeConfig` runs which updates `SITE_NAME`. Due to that thing, it shows `Authn | null` which is not a good user experience. I will suggest to remove `| <%= process.env.SITE_NAME %>` and its better to just show `Authn` only in title.  Here is the screenshot:

<img width="1471" alt="Screenshot 2024-02-09 at 10 12 25 AM" src="https://github.com/openedx/frontend-app-authn/assets/112946189/6ace0fb0-e3fc-4417-ace8-fc0db4796fe0">

I am running openedx using `tutor local`

**Comment by regisb** [comment]
Hi Hina! :wave: Removing the entire `| <%= process.env.SITE_NAME %>` is going to be a breaking change for every Open edX platform out there, and a very debatable one.

Can I suggest instead to only remove the site name when it's null? That way, the title would be "Authn" while loading the page, and then become "Authn | site_name" once `mergeConfig` is run. Is that even possible?

A separate question would be to rename the "Authn" title to "Authentication". I think there's consensus to say that "Authn" makes for a terrible site name.

**Comment by attiyaIshaque** [comment]
@hinakhadim The issue has been resolved in Pull Request https://github.com/openedx/frontend-app-authn/pull/1168, and I am  closing the PR with the resolution of "Fixed."

**Comment by attiyaIshaque** [comment]
@regisb I have implemented this suggested change.
> Can I suggest instead to only remove the site name when it's null? That way, the title would be "Authn" while loading the page, and then become "Authn | site_name" once `mergeConfig` is run. Is that even possible?
>

**Comment by zainab-amir** [comment]
>  I think there's consensus to say that "Authn" makes for a terrible site name.

I agree. @attiyaIshaque lets create a follow up PR to do this too.

**Comment by hinakhadim** [comment]
Hi all, I have tested the fixed PR #1168  on my machine. It haven't resolved the issue for me. It treats `null` as string and pass the condition which should be failed. I have created another PR #1185. I kindly request your assistance in reviewing this latest submission.
