### ISSUE TITLE
Signin API not found!

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/frontend-app-authn#470]
hey guys, I just installed this mfe alongside my lilac.rc3 open edx and SignIn functionality doesn't work
maybe the API changed or something but I couldn't access this URL. it returned 404.

LMS/api/user/v2/account/login_session/
which was used here: 
 
https://github.com/edx/frontend-app-authn/blob/32300db8dd44effaffa6e9980887d8556543cfc1/src/login/data/service.js#L14
note that register function worked like a charm.

**Comment by waheedahmed** [comment]
Hi @CodeWithEmad, this endpoint is not available in lilac and is only available from maple onwards. You either need to upgrade to `open-release/maple.master` or need to port the change manually. Thanks!
