### ISSUE TITLE
Regression: Olive UI breaks for long site names

### ISSUE THREAD

**Issue by throwaway-a** [openedx/frontend-app-authn#929]
When an Open edX site has a long name, the new registration/login page UI bisects the site-name. See here for image of issue: https://discuss.openedx.org/t/how-to-get-rid-of-diagonal-line-in-sign-in-page-in-indigo-on-olive/10182

This is a regression from pre-Olive behavior.

**Comment by zainab-amir** [comment]
@throwaway-a we have now provided a new design for the base component that doesn't have the site name but just the site logo. 
<img width="1438" alt="Screenshot 2023-06-28 at 3 35 03 PM (1)" src="https://github.com/openedx/frontend-app-authn/assets/40633976/b8d458de-8e02-4222-9538-c815bbd1c22d">

**Comment by zainab-amir** [comment]
@throwaway-a I have created a ticket in the backlog to put documentation in the README file. I will update here once it's done.

**Comment by zainab-amir** [comment]
The documentation to switch between base containers is added here: https://github.com/openedx/frontend-app-authn/blob/master/docs/how_tos/modifying_base_container.rst
