### ISSUE TITLE
Regression? Terms of Service and Privacy Policy links broken on registration page

### ISSUE THREAD

**Issue by throwaway-a** [openedx/frontend-app-authn#931]
Under the new student registration page is the following text/code with broken links:
```
By creating an account, you agree to the [Terms of Service and Honor Code](https://apps.test.mydomain.com/authn/register?next=%2F#)
[in a new tab](https://apps.test.mydomain.com/authn/register?next=%2F#) and you acknowledge that MyLongSiteNameTest and each Member process your personal data in accordance with the [Privacy Policy](https://apps.test.mydomain.com/authn/register?next=%2F#)
[in a new tab](https://apps.test.mydomain.com/authn/register?next=%2F#).
```

Those "Terms of Service and Honor Code" and "Privacy Policy" links are broken by default, and go nowhere, except back to the registration page itself.

FWIW on my previous instance (which is using tutor indigo theme, though I don't know if that matters), the URL for the terms of service is "test.mydomain.com/tos". I think that was the default URL.

Is this expected breakage, and there's somewhere I'm supposed to change these URLs? Or is this unexpected breakage that just no one has reported yet for Olive.3?

**Comment by zainab-amir** [comment]
Have you set these links in your settings? https://github.com/openedx/frontend-app-authn/blob/master/src/config/index.js#L18-L20
The default value is null and that is why it is redirecting you back to registration form. You need to add the links for your site's terms of services and honor code policy.

**Comment by zainab-amir** [comment]
I am closing as I haven't received a response on this
